extends: eslint-config-airbnb-base

env:
  node:  true
  es6:   true
  mocha: true

parser: "babel-eslint"

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true

rules:
  key-spacing:
    - 2
    -
      mode:        "minimum"
      align:       "value"
      beforeColon: false
  no-multi-spaces:
    - 0
    -
      exceptions:
        ImportDeclaration:        true
        VariableDeclarator:       true
        ArrowFunctionExpression:  true
  comma-dangle:
    - error
    - never
  max-len:
    - 2
    - code: 150
  no-confusing-arrow:
    - error
    - allowParens: true

  no-return-assign:     0
  no-use-before-define: off

globals:
  should: true
